2020-04-28 23:13:24,981 ERROR: Exception on /index [GET] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 41, in index
    return render_template('index.html',title='Home Page',form=form,posts=posts)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\WORK\FlaskProject\flaskApp\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\WORK\FlaskProject\flaskApp\templates\base.html", line 32, in top-level template code
    {%block content%}{%endblock%}
  File "D:\WORK\FlaskProject\flaskApp\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-04-28 23:13:33,232 ERROR: Exception on /index [GET] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 41, in index
    return render_template('index.html',title='Home Page',form=form,posts=posts)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\ankit\anaconda3\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\WORK\FlaskProject\flaskApp\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\WORK\FlaskProject\flaskApp\templates\base.html", line 32, in top-level template code
    {%block content%}{%endblock%}
  File "D:\WORK\FlaskProject\flaskApp\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-04-28 23:15:14,113 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
2020-04-28 23:45:13,002 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
2020-04-28 23:47:16,061 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
2020-04-28 23:58:57,915 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
2020-04-28 23:59:32,078 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
2020-04-28 23:59:38,155 ERROR: Exception on /user/ankitvs [GET] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 89, in user
    page = request.args.get('page', q, type=int)
NameError: name 'q' is not defined
2020-04-29 00:00:27,956 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:56]
